<template>
  <div v-if="open" class="backdrop" @click="$emit('close')"></div>
  <!-- Comenting out the element to leave only one root element here to receive
  the ttransformation classes generated by Vue -->
  <transition name="modal">
    <!-- I wrapped the dialog element with the transition element to allow the animation
    without having to comment out the backdrop.
    However, the v-if command is in the parent component, so the animaiton doesn't happe.
    To solve that, I can create the :open binded component to send the data and pass it down
    as props. -->
  <dialog open v-if="open">
    <slot></slot>
  </dialog>
  </transition>
</template>

<script>
export default {
  props: ['open'],
  emits: ['close']
};
</script>

<style scoped>
.backdrop {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100vh;
  z-index: 10;
  background-color: rgba(0, 0, 0, 0.75);
}

dialog {
  position: fixed;
  top: 30vh;
  width: 30rem;
  left: calc(50% - 15rem);
  margin: 0;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.26);
  border-radius: 12px;
  padding: 1rem;
  background-color: white;
  z-index: 100;
  border: none;
  /* animation: modal 0.3s ease-out forwards; */
  /* The animation will start when the element is rendered and is a part of the page.
  Vue is helping with that.
  I can't play an animation when the element is leaving the page. That's when Vue coming in handy
  Vue can delay the disapearing until the animation is finnished. */
}

.modal-enter-active {
  animation: modal 0.3s ease-out;
}

.modal-leave-active {
  animation: modal 0.3s ease-in reverse;
  /* The reverse keyword makes the animation in reverse in this class. */
}

@keyframes modal {
  from {
    opacity: 0;
    transform: translateY(-50px) scale(0.9);
  }

  to {
    opacity: 1;
    transform: translateY(0) scale(1);
  }
}
</style>
